Separate roles logged in and logged out
engineering89-job-project-group-2/project pull request #35
Opened 2021-07-20 15:19 UTC by saim22r

Not sure how to separate pages on html and routes.py

2021-07-20 16:03 UTC, monotiller commented on app/roles_database.py
> +        if 'username' in session:
This line will need to be moved in to `routes.py`. We'll discuss more tomorrow

2021-07-20 16:03 UTC, monotiller requested changes
Some small tweaks to the code which we'll do tomorrow! @Ahhhh-man

2021-07-20 18:53 UTC, Ahhhh-man commented
Do not merge. This doesn't work for me. roles and search pages outputs "Internal Server Error". 
"TypeError: 'NoneType' object is not iterable".

2021-07-20 22:42 UTC, Ahhhh-man requested changes

2021-07-20 22:42 UTC, Ahhhh-man commented on app/routes.py
> +    return render_template('search.html', title='Search', form=search_form, data=RolesDatabase().view_sorted_roles_logged_out('job_role', 'ASC'))
If I'm signed in, the logged out function is still called, and nothing is return. This will cause a 500 Internal Server Error.

2021-07-20 22:42 UTC, Ahhhh-man commented on app/templates/roles.html
> +            <h1>Please log in to view more jobs!</h1>
This line will be visiable even after I login. Flask flash can be used to avoid this.

2021-07-20 22:42 UTC, Ahhhh-man commented on app/roles_database.py
> +            return all_roles
else case needed.

2021-07-20 22:42 UTC, Ahhhh-man commented on app/routes.py
> +                           data=RolesDatabase().view_sorted_roles_logged_out(category, sort_order), download=download)
If I'm signed in, the logged out function is still called, and nothing is return. This will cause a 500 Internal Server Error.

2021-07-21 09:05 UTC, monotiller commented on app/templates/roles.html
> +            <h1>Please log in to view more jobs!</h1>
This is a flash:
```python
flash("Invalid username or password")
```

2021-07-21 09:07 UTC, monotiller commented
@Ahhhh-man adapted this code separately in own branch. See #37 for more details!

2021-07-21 09:07 UTC, closed without merging