Tom
engineering89-job-project-group-2/project pull request #36
Opened 2021-07-20 16:06 UTC by twilliams9397

for review before merging

2021-07-20 22:42 UTC, Ahhhh-man requested changes

2021-07-20 22:42 UTC, Ahhhh-man commented on TDD/TDD.py
> +        self.connection = sqlite3.connect('test_database')
duplicate connections

2021-07-20 22:42 UTC, Ahhhh-man commented on app/vacancies_scraping.py
> +print(vacancy_list)
While this scraps the data, I'm unsure about the usefulness. This is beacause we need to extract to the db, but the form is in [name, location - company, desc]. View below for an actual example. Will discuss issue tomorrow. 

`
['Full Stack Developer\r', 'London - IO Associates\r', 'Full-Stack JavaScript Developer (React / NodeJS / AWS) Outside IR35 - Fully Remote - £500 to £550 Per/Day - 6 Months. iO Associates are delighted to be partnered with an exciting consultancy client based in London who is looking for not one but. 2x Full-Stack JavaScript Developers. with experience of React, NodeJS and AWS to join their team ASAP. They work with a range of Private, PubSec & Boutique Consultancy... more ▸\r', 'Posted: 20 minutes ago']
`

2021-07-21 09:12 UTC, monotiller commented on TDD/TDD.py
> +        dbc.add_role('test_role', '1', '0', '50000', '0', '300', '2500')
Use the production version here. In `roles_database.py` the class is `RoleDatabase.add_role()`

2021-07-21 09:12 UTC, monotiller commented on TDD/TDD.py
> +        self.connection.commit()
See here: https://github.com/engineering89-job-project-group-2/project/pull/36/files#r673801546

2021-07-21 09:21 UTC, monotiller approved these changes
Use to develop today!

2021-07-21 09:22 UTC, merged